variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "4"
  ORD_SOUMET_TMPFS: "1G"
  ORD_SOUMET_M: "8G"
  ORD_SOUMET_W: "30"
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build

before_script:
  - export CLICOLOR_FORCE=1
  - source ~/ci-admin/env/init.sh
  - export PIPELINE_SUBDIR=${ECCI_BUILD_DIR}/precaution/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}

# U2 Intel 2022 with installed RPN-SI libs
# Used for SSM package
build:rhel-8-icelake-64-intel-2022.1.2:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ${ECCI_ENV}/latest/profile.sh
    - set -e
    - . ./.eccc_setup_intel
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2022.1.2
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2022.1.2 .
    - ./scripts/link-dbase.sh
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
    - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
    - time make -j $NCPUS
    - time make work
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-8-icelake-64-intel-2022.1.2
    - gem_dbase
    - scm_dbase

